<?php
session_start();
include 'connect.php';
$user_id = $_SESSION['user_id'];

if (!isset($_SESSION['user_id'])) {
  header("Location: index.php");
  exit();
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>FoHSS</title>
  <link rel="stylesheet" href="">
  <link rel="stylesheet" href="header.css">
  <link rel="stylesheet" href="./Assert/css/bootstrap.min.css">

  <style>
    .center {
      text-align: center;
    }

    .btn-fixed {
      width: 80px;
    }
  </style>
</head>

<body>
  <header>
    <div class="logo-container">
      <img src="FoHSS.png" alt="Website Logo">
      <h1>Faculty Meeting Management System</h1>
    </div>

    <nav>
      <a href="user_home.php">Home</a>
      <a href="user_attendance.php">Attendance</a>
      <a href="user_profile.php">Profile</a>
    </nav>
  </header>

  <main>
    <section class="content">
      <h2>Meeting Shedules & Documents</h2>
      <form class="search-box" method="POST">
        <input type="text" name="search" placeholder="Enter text..." required>
        <button type="submit">Search</button>
      </form>


      <?php
      if (isset($_POST['search'])) {
        $search = $_POST['search'];

        // Fetch all files from database
        $result = mysqli_query($conn, "SELECT * FROM meeting_file");

        while ($row = mysqli_fetch_assoc($result)) {
          $file = $row['file_name'];  
          $txt = "files/" . pathinfo($file, PATHINFO_FILENAME) . ".txt"; // text file generated by OCR

          if (file_exists($txt)) {
            $content = file_get_contents($txt);

           
            if (stripos($content, $search) !== false) {
              echo "<p><a href='files/$file' target='_blank'>$file</a></p>";
            }
          }
        }
      }
      ?>
      <div class="table-container">
        <table class="table table-striped">
          <thead>
            <tr>
              <th colspan="8" class="center">Meeting Shedule & Document</th>
            </tr>
            <tr>
              <th colspan="8" class="center">Faculty of Humanities & Social Sciences</th>
            </tr>
            <tr>
              <th>Meeting Name</th>
              <th>Meeting Date</th>
              <th>Meeting Time</th>
              <th>Meeting Description</th>
              <th>Document</th>

            </tr>
          </thead>
          <tbody>
            <?php
            $sql1 = "SELECT 
                 m.name,
                 s.schedule_id,
                 s.schedule_date,
                 s.schedule_time,
                 s.description AS schedule_description,
                 f.file_name, 
                 f.description AS file_description,
                 f.date,
                 f.time,
                 f.file_id
                 FROM 
                 meeting m
                 INNER JOIN 
                 schedule s ON m.meeting_id = s.meeting_id
                 INNER JOIN
                 meeting_file f ON s.schedule_id = f.schedule_id
                 ORDER BY 
                 s.schedule_date ASC;";
            $result = mysqli_query($conn, $sql1);
            if (mysqli_num_rows($result) > 0) {
              while ($row = mysqli_fetch_assoc($result)) {
                $name = $row['name'];
                $file_id = $row['file_id'];
                $schedule_date = $row['schedule_date'];
                $schedule_time = $row['schedule_time'];
                $description = $row['schedule_description'];
                $schedule_id = $row['schedule_id'];
                $path = "files/" . $row['file_name'];

                $formatted_date = date("d M Y", strtotime($row['schedule_date']));
                $formatted_time = date("h:i A", strtotime($row['schedule_time']));




                echo "<tr>
                     <td>$name</td>
                     <td>$formatted_date</td>
                     <td>$formatted_time</td>
                     <td>$description</td>
                     <td><a href='$path' target='_blank'>View PDF</a></td>
                    
                
                  </tr>";
              }
            }
            ?>
          </tbody>
        </table>
      </div>



      <?php


      // Get schedules for next 14 days for this user
      $sql = "SELECT m.name AS meeting_name, 
               s.schedule_date, 
               s.schedule_time, 
               s.description
        FROM schedule s
        INNER JOIN meeting m ON s.meeting_id = m.meeting_id
        INNER JOIN participant p ON m.meeting_id = p.meeting_id
        WHERE p.user_id = $user_id
        AND s.schedule_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 14 DAY)
        ORDER BY s.schedule_date ASC";

      $result = $conn->query($sql);
      ?>




    </section>
    <aside>
      <h3>Upcoming Meetings</h3>
      <?php
      if ($result->num_rows > 0) {
        while ($row = $result->fetch_assoc()) {
          echo "<div style='padding:10px; margin-bottom:10px; border:1px solid #ccc; border-radius:8px; background:#fff;'>";
          echo "<strong>" . $row['meeting_name'] . "</strong><br>";
          echo "Date: " . $row['schedule_date'] . "<br>";
          echo "Time: " . $row['schedule_time'];
          echo "</div>";
        }
      } else {}
      ?>
    </aside>

  </main>



  <footer>
    &copy; 2025 Faculty Board Website. All rights reserved.
  </footer>
  <script src="./Assert/js/bootstrap.min.js"></script>
</body>

</html>